## CDades Sprint 3 Tasca 1

**Exercici 1**
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [2]:
import numpy as np
from numpy import random
from scipy import stats

In [5]:
def dimension(array):
    print("Dimensión del array:" + str(array.ndim))
    if array.ndim > 1:  # Cálculo de la dimensión
        print('Este array no es válido')
    else:
        descriptiveStatistics = stats.describe(array)  # Resumen estadístico
        print("Resumen estadístico del array: ")
        print("Número de elementos: " + str(descriptiveStatistics.nobs))
        print("Valor mínimo: " + str(descriptiveStatistics.minmax[0]))
        print("Valor máximo: " + str(descriptiveStatistics.minmax[1]))
        print("Media: " + str(descriptiveStatistics.mean))
        print("Varianza: " + str(descriptiveStatistics.variance)) 
        print("Skewness: " + str(descriptiveStatistics.skewness))
        print("Kurtosis: " + str(descriptiveStatistics.kurtosis))
        
array = [] # Definimos en array
a = int(input("Size of array:")) # Entrada de longitud del array
for i in range(a):
    array.append(float(input("Element:"))) # Entrada de valores del array y paso de string a float
# print(type(array))  Aquí el array es tipo lista
array = np.array(array) # Paso de lista a tipo numpy.ndarray
# print(type(array)) Aquí el array es tipo numpy.ndarray
print('El array es: ')
print(np.floor(array))  # Floor redondea a entero
# print(array.dtype)

dimension(array)


Size of array:4
Element:2
Element:5
Element:8
Element:99
El array es: 
[ 2.  5.  8. 99.]
Dimensión del array:1
Resumen estadístico del array: 
Número de elementos: 4
Valor mínimo: 2.0
Valor máximo: 99.0
Media: 28.5
Varianza: 2215.0
Skewness: 1.1453265050018868
Kurtosis: -0.6738730218582853


**Exercici 2**
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [32]:
def matrizNxN(N):
    matriz = random.randint(100, size=(N,N))
    print('La matriz resultante es:')
    print(matriz)
    
dim = int(input('Introduce el número de filas de tu matriz: '))

matrizNxN(dim)

Introduce el número de filas de tu matriz: 3
La matriz resultante es:
[[85 40 35]
 [23 45 76]
 [89 97 75]]


**Exercici 3**
Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [31]:
def matrizNxM(N,M):
    matriz = random.randint(100, size=(N,M))
    print('La matriz resultante es:')
    print(matriz)
    sumaFilas = np.sum(matriz, axis=1)
    sumaColumnas = np.sum(matriz, axis=0)
    for x in range(N):
        print('El total de la fila ' + str(x) + ' es: ' + str(sumaFilas[x]))
    for y in range(M):
        print('El total de la columna ' + str(y) + ' es: ' + str(sumaColumnas[y]))       
    
N = int(input('Introduce el número de filas de tu matriz: '))
M = int(input('Introduce el número de filas de tu matriz: '))

matrizNxM(N,M)

Introduce el número de filas de tu matriz: 3
Introduce el número de filas de tu matriz: 4
La matriz resultante es:
[[32 25 54 11]
 [36 25 43 29]
 [94 74 54 34]]
El total de la fila 0 es: 122
El total de la fila 1 es: 133
El total de la fila 2 es: 256
El total de la columna 0 es: 162
El total de la columna 1 es: 124
El total de la columna 2 es: 151
El total de la columna 3 es: 74


**Exercici 4**
Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [33]:
def corrcoef(matriz):
    coefCorr=np.corrcoef(matriz)
    print(coefCorr)
N = int(input('Introduce el número de filas de tu matriz: '))
M = int(input('Introduce el número de filas de tu matriz: '))
matriz = random.randint(100, size=(N,M))
print('La matriz resultante es:')
print( matriz)
print('El coeficiente de correlación es:')
corrcoef(matriz)

Introduce el número de filas de tu matriz: 3
Introduce el número de filas de tu matriz: 4
La matriz resultante es:
[[62 69 60 38]
 [38 53 96 96]
 [15 96  2 99]]
El coeficiente de correlación es:
[[ 1.         -0.65185823 -0.33744898]
 [-0.65185823  1.          0.07686823]
 [-0.33744898  0.07686823  1.        ]]
